awk=$(command -v awk)
cat=$(command -v cat)
chmod=$(command -v chmod)
chown=$(command -v chown)
curl=$(command -v curl)
cp=$(${debug}command -v cp)
date=$(command -v date)
grep=$(command -v grep)
gpg=$(command -v gpg)
ls=$(command -v ls)
od=$(command -v od)
pax="${debug}$(command -v pax) -rwpe"
pkgin="$(command -v pkgin)"
pkg_info="$(command -v pkg_info)"
mkdir="$(command -v mkdir) -p"
rm="$(command -v rm) -f"
rsync="$(command -v rsync) -av"
shasum=$(command -v shasum)
sort=$(command -v sort)
sudo=$(command -v sudo)
sleep=$(command -v sleep)
tar=$(command -v tar)
touch=$(command -v touch)
tr=$(command -v tr)
umount=$(command -v umount)
ARCH=$(uname -m)
DDATE=$(date +%Y%m%d)
OS=$(uname -s)
SHELLRC=~/.$(echo $SHELL | awk -F/ '{print$NF}')rc
PKGIN_VARDB="/var/db/pkgin"
