awk=$(which awk)
cat=$(which cat)
chmod=$(which chmod)
chown=$(which chown)
chroot=$(which chroot)
curl=$(which curl)
cp=$(${debug}which cp)
date=$(which date)
grep=$(which grep)
gpg=$(which gpg)
id=$(which id)
ls=$(which ls)
od=$(which od)
pax="${debug}$(which pax) -rwpe"
pkgin="$(which pkgin)"
pkg_info="$(which pkg_info)"
mkdir="$(which mkdir) -p"
rm="$(which rm) -f"
rsync="$(which rsync) -av"
sh=$(which sh)
shasum=$(which shasum)
sort=$(which sort)
sudo=$(which sudo)
sleep=$(which sleep)
tar=$(which tar)
touch=$(which touch)
tr=$(which tr)
umount=$(which umount)
ARCH=$(uname -m)
DDATE=$(date +%Y%m%d)
OS=$(uname -s)
SHELLRC=~/.$(echo $SHELL | awk -F/ '{print$NF}')rc
PKGIN_VARDB="$(${pkg_info} -QVARBASE pkgin)/db/pkgin"
