cat=$(command -v cat)
sh=$(command -v sh)
id=$(command -v id)
pax="${debug}$(command -v pax) -rwpe"
cp=$(${debug}command -v cp)
chown=$(command -v chown)
chmod=$(command -v chmod)
awk=$(command -v awk)
sort=$(command -v sort)
grep=$(command -v grep)
tar=$(command -v tar)
mkdir="$(command -v mkdir) -p"
touch=$(command -v touch)
rm="$(command -v rm) -f"
ls=$(command -v ls)
od=$(command -v od)
tr=$(command -v tr)
mount=$(command -v mount)
umount=$(command -v umount)
curl=$(command -v curl)
ifconfig=$(command -v ifconfig)
useradd=$(command -v useradd)
groupadd=$(command -v groupadd)
ping=$(command -v ping)
OS=$(uname -s)
pkg_info=$(command -v pkg_info)

# columns sizes for ls
cols=${COLUMNS:-$(tput cols)}
col1=$(($((${cols} * 23)) / 100))
col2=$(($((${cols} * 22)) / 100))
col3=$(($((${cols} * 30)) / 100))
col4=$(($((${cols} * 10)) / 100))
